version: '3'

services:
  node1:
    build: .
    container_name: node1
    command: memcoin --config /tmp/node1 start --port 2001
    network_mode: "host"
    volumes:
      - type: bind
        source: ./nodedata
        target: /tmp
    # ports:
    #   - "2001:2001"
    #   - "8081:8081"
  node2:
    build: .
    container_name: node2
    command: memcoin --config /tmp/node2 start --port 2002
    network_mode: "host"
    volumes:
      - type: bind
        source: ./nodedata
        target: /tmp
    # ports:
    #   - "2002:2002"
    #   - "8082:8082"
  node3:
    build: .
    container_name: node3
    command: memcoin --config /tmp/node3 start --port 2003
    network_mode: "host"
    volumes:
      - type: bind
        source: ./nodedata
        target: /tmp
    # ports:
    #   - "2003:2003"
    #   - "8083:8083"

  nodetest:
    build: .
    container_name: nodetest
    network_mode: "host"
    volumes:
      - type: bind
        source: ./nodedata
        target: /tmp