name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17


    - name: Test cli
      run: go test -cover ./cli/...
      
    - name: Test Contract
      run: go test -cover ./contracts/...
    
    - name: Test Shuffle
      run: go test -cover ./services/shuffle/...
      
    #- name: Test DKG
      #run: go test -cover ./services/dkg/...
