name: Go Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ^1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        
      - name: Test integration & benchmark with coverage
        run: go test -bench -cover -tags=integration ./test/...
