name: Go Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17


    - name: Test cli
      run: go test -cover ./cli/cosipbftcontroller/... #does not include memcoin
      
    - name: Test Contract
      run: go test -cover ./contracts/...
    
    - name: Test Shuffle
      run: go test -cover ./services/shuffle/...
      
    - name: Test Contract with coverage
      run: go test -json -covermode=count -coverprofile=profile.cov ./contracts/... > report.json
      
    #- name: Test DKG
      #run: go test -cover ./services/dkg/...